#DB
POSTGRESQL_USERNAME: postgres
POSTGRESQL_PASSWORD: 1
POSTGRESQL_HOST: localhost
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: test

#Server
CONTAINER_PORT: 8080
ACTIVE_PROFILE: changeThis

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: mygmail@gmail.com
EMAIL_PASSWORD: mypassword
VERIFY_EMAIL_HOST: http://localhost.com:8080